const MONTHS=["","Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"],$=s=>document.querySelector(s);let tab="painel",db;
const DBN="tcesp-mendonca-v3",STORE="dados",KEY="base";
function idbOpen(){return new Promise((res,rej)=>{let r=indexedDB.open(DBN,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function idbGet(){let d=await idbOpen();return new Promise((res,rej)=>{let r=d.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function save(){let d=await idbOpen();return new Promise((res,rej)=>{let r=d.transaction(STORE,"readwrite").objectStore(STORE).put(db,KEY);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function brl(v){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0)} function n(v){return +v||0} function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function orgMatch(raw,filter){if(filter==="Todos")return true;let o=String(raw||"").toUpperCase();if(filter==="Prefeitura")return o.includes("PREFEITURA");if(filter==="Câmara")return o.includes("CÂMARA")||o.includes("CAMARA");return true}
function baseFilt(arr,withOrg=false){let m=+$("#mes").value,q=$("#q").value.toLowerCase(),o=$("#orgao").value;return arr.filter(x=>x.ano==+$("#ano").value&&(!m||x.mesNum==m)&&(!withOrg||orgMatch(x.orgao,o))&&(!q||JSON.stringify(x).toLowerCase().includes(q)))}
function evSums(d){let e={};d.forEach(x=>e[x.evento]=(e[x.evento]||0)+n(x.valor));return e} function net(e){return n(e.Empenhado)+n(e.Reforço)-n(e.Anulação)}
function supplierGroups(d){let g={};d.forEach(x=>{let id=x.fornecedorId||("NOME:"+(x.fornecedor||"(sem nome)")),k=id;g[k]??={id,nome:x.fornecedor||"(sem nome)",e:{}};if((x.fornecedor||"").length>g[k].nome.length)g[k].nome=x.fornecedor;g[k].e[x.evento]=(g[k].e[x.evento]||0)+n(x.valor)});return Object.values(g)}
function cards(){let d=baseFilt(db.despesas,true),r=baseFilt(db.receitas,false),e=evSums(d),rec=r.reduce((a,x)=>a+n(x.valor),0),nl=net(e),saldo=rec-nl;$("#cards").innerHTML=[["Receita",rec],["Empenhado",e.Empenhado],["Reforço",e.Reforço],["Anulação",e.Anulação],["Empenho líquido",nl],["Liquidado",e["Valor Liquidado"]],["Pago",e["Valor Pago"]]].map((x,i)=>`<div class="metric card ${i===4?'emph':''}"><small>${x[0]}</small><strong>${brl(x[1])}</strong></div>`).join("")+`<div class="metric card emph"><small>Receita − empenho líquido</small><strong>${brl(saldo)}</strong></div>`}
function canvasSetup(c){let r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=r.height*dpr;let x=c.getContext("2d");x.scale(dpr,dpr);return {x,w:r.width,h:r.height}}
function pie(c,data){let {x,w,h}=canvasSetup(c),tot=data.reduce((a,b)=>a+b.v,0),cx=w*.38,cy=h*.48,R=Math.min(w,h)*.32,a=-Math.PI/2,colors=["#17324d","#2f6fa5","#4f8fba","#6ba5c8","#87b8d4","#a2c9df","#c0d9e7","#d5e5ee","#78909c","#9aa7b0","#c8d0d5"];data.forEach((z,i)=>{let da=tot?z.v/tot*Math.PI*2:0;x.beginPath();x.moveTo(cx,cy);x.arc(cx,cy,R,a,a+da);x.closePath();x.fillStyle=colors[i%colors.length];x.fill();a+=da});x.font="11px Segoe UI";data.slice(0,11).forEach((z,i)=>{let yy=18+i*25,xx=w*.72;x.fillStyle=colors[i%colors.length];x.fillRect(xx,yy,10,10);x.fillStyle="#26333d";let nm=z.n.length>24?z.n.slice(0,23)+"…":z.n;x.fillText(nm,xx+15,yy+9);x.fillStyle="#66727e";x.fillText((tot?z.v/tot*100:0).toFixed(1).replace(".",",")+"%",xx+15,yy+21)})}
function lines(c,series){let {x,w,h}=canvasSetup(c),pad={l:55,r:15,t:18,b:35},vals=series.flatMap(s=>s.v),max=Math.max(...vals,1),min=Math.min(0,...vals),colors=["#17324d","#2f6fa5","#8b5e3c"];x.font="10px Segoe UI";x.strokeStyle="#dfe5e9";for(let i=0;i<=4;i++){let y=pad.t+(h-pad.t-pad.b)*i/4;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();let v=max-(max-min)*i/4;x.fillStyle="#66727e";x.fillText((v/1e6).toFixed(1)+" mi",3,y+3)}let months=Array.from({length:12},(_,i)=>i+1).filter(m=>!+$("#mes").value||m==+$("#mes").value);months.forEach((m,i)=>{let xx=pad.l+(w-pad.l-pad.r)*(months.length===1?.5:i/(months.length-1));x.fillStyle="#66727e";x.fillText(MONTHS[m].slice(0,3),xx-8,h-12)});series.forEach((s,si)=>{x.strokeStyle=colors[si];x.lineWidth=2;x.beginPath();s.v.forEach((v,i)=>{let xx=pad.l+(w-pad.l-pad.r)*(s.v.length===1?.5:i/(s.v.length-1)),yy=pad.t+(max-v)/(max-min||1)*(h-pad.t-pad.b);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke()})}
function bars(c,data){let {x,w,h}=canvasSetup(c),pad={l:160,r:15,t:10,b:15},max=Math.max(...data.map(z=>z.v),1),bh=(h-pad.t-pad.b)/data.length*.65,gap=(h-pad.t-pad.b)/data.length;x.font="10px Segoe UI";data.forEach((z,i)=>{let y=pad.t+i*gap;x.fillStyle="#2f6fa5";x.fillRect(pad.l,y,(w-pad.l-pad.r)*z.v/max,bh);x.fillStyle="#26333d";let nm=z.n.length>24?z.n.slice(0,23)+"…":z.n;x.fillText(nm,3,y+bh*.75);x.fillText((z.v/1e6).toFixed(2).replace(".",",")+" mi",pad.l+4,y+bh*.75)})}
function renderPanel(){let d=baseFilt(db.despesas,true),r=baseFilt(db.receitas,false),groups=supplierGroups(d),paid=groups.map(g=>({n:g.nome,v:n(g.e["Valor Pago"]),id:g.id})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v),top10=paid.slice(0,10),others=paid.slice(10).reduce((a,x)=>a+x.v,0);if(others>0)top10.push({n:"Demais credores",v:others});let months=Array.from({length:12},(_,i)=>i+1).filter(m=>!+$("#mes").value||m==+$("#mes").value),monthly=(kind)=>months.map(m=>{if(kind==="rec")return db.receitas.filter(x=>x.ano==+$("#ano").value&&x.mesNum==m).reduce((a,x)=>a+n(x.valor),0);let dd=db.despesas.filter(x=>x.ano==+$("#ano").value&&x.mesNum==m&&orgMatch(x.orgao,$("#orgao").value),e=evSums(dd);return kind==="net"?net(e):n(e["Valor Pago"])});
$("#painel").innerHTML=`<section class="chartcard card"><h3>Despesa paga por credor</h3><p>10 maiores credores + demais, conforme o filtro atual.</p><div class="chartbox"><canvas id="pie"></canvas></div></section><section class="chartcard card"><h3>Receita × empenho líquido × pago</h3><p>Evolução mensal. Empenho líquido = empenhado + reforço − anulação.</p><div class="chartbox"><canvas id="line"></canvas></div><div class="barlegend">Receita • Empenho líquido • Pago</div></section><section class="chartcard card"><h3>20 maiores pagamentos</h3><p>Ranking por credor, agrupado prioritariamente pelo identificador/CNPJ.</p><div class="chartbox" style="height:520px"><canvas id="bars"></canvas></div></section><section class="rank card"><h3>Ranking — 20 maiores credores por valor pago</h3><div class="rankgrid">${paid.slice(0,20).map((z,i)=>`<div class="rankrow"><span class="badge">${i+1}</span><span>${esc(z.n)}<small style="display:block;color:#77838d">${esc(z.id)}</small></span><b>${brl(z.v)}</b></div>`).join("")}</div></section>`;requestAnimationFrame(()=>{pie($("#pie"),top10);lines($("#line"),[{v:monthly("rec")},{v:monthly("net")},{v:monthly("paid")}]);bars($("#bars"),paid.slice(0,20))})}
function renderTable(){let d=baseFilt(db.despesas,true),r=baseFilt(db.receitas,false),rows=[],heads=[];if(tab==="despesas"){heads=["Valor","Mês","Evento","Empenho","Data","Órgão","Fornecedor","Identificação"];rows=d.sort((a,b)=>b.valor-a.valor).map(x=>[brl(x.valor),x.mes,x.evento,x.empenho,x.data,x.orgao,x.fornecedor,x.fornecedorId])}if(tab==="receitas"){heads=["Valor","Mês","Fonte","Aplicação","Natureza / alínea","Subalínea"];rows=r.sort((a,b)=>b.valor-a.valor).map(x=>[brl(x.valor),x.mes,x.fonte,x.aplicacao,x.alinea,x.subalinea])}if(tab==="fornecedores"){heads=["Fornecedor","Identificação","Empenhado","Reforço","Anulação","Empenho líquido","Liquidado","Pago"];rows=supplierGroups(d).map(g=>[g.nome,g.id,brl(g.e.Empenhado),brl(g.e.Reforço),brl(g.e.Anulação),brl(net(g.e)),brl(g.e["Valor Liquidado"]),brl(g.e["Valor Pago"])]).sort((a,b)=>money(b[7])-money(a[7]))}$("#thead").innerHTML="<tr>"+heads.map(h=>`<th>${h}</th>`).join("")+"</tr>";$("#tbody").innerHTML=rows.map(r=>"<tr>"+r.map(v=>`<td>${esc(v)}</td>`).join("")+"</tr>").join("");return rows.length}
function money(s){return +(s||"").replace(/[^\d,-]/g,"").replace(/\./g,"").replace(",",".")}
function audit(){let d=baseFilt(db.despesas,true),r=baseFilt(db.receitas,false),e=evSums(d),exactDup=a=>{let s=new Set(),c=0;a.forEach(x=>{let k=JSON.stringify(x);s.has(k)?c++:s.add(k)});return c},zero=d.filter(x=>n(x.valor)===0).length,negL=d.filter(x=>x.evento==="Valor Liquidado"&&x.valor<0).length,negP=d.filter(x=>x.evento==="Valor Pago"&&x.valor<0).length,negR=r.filter(x=>x.valor<0).length,ids={};d.forEach(x=>{if(x.fornecedorId)(ids[x.fornecedorId]??=new Set()).add(x.fornecedor)});let aliases=Object.values(ids).filter(s=>s.size>1).length;
$("#auditSec").innerHTML=`<div class="auditgrid"><div class="audititem card ok"><small>Registros de despesas</small><strong>${d.length.toLocaleString("pt-BR")}</strong><small>Filtro atual</small></div><div class="audititem card ${exactDup(d)?'warn':'ok'}"><small>Duplicatas exatas — despesas</small><strong>${exactDup(d)}</strong><small>Não são removidas automaticamente.</small></div><div class="audititem card ${exactDup(r)?'warn':'ok'}"><small>Duplicatas exatas — receitas</small><strong>${exactDup(r)}</strong><small>Preservadas: a API não fornece ID transacional.</small></div><div class="audititem card warn"><small>Eventos de valor zero</small><strong>${zero}</strong><small>Informativos/atípicos; preservados.</small></div><div class="audititem card warn"><small>Estornos de liquidação / pagamento</small><strong>${negL} / ${negP}</strong><small>Valores negativos preservados nos totais.</small></div><div class="audititem card warn"><small>Receitas negativas</small><strong>${negR}</strong><small>Deduções preservadas no total líquido.</small></div><div class="audititem card warn"><small>Identificadores com grafias distintas</small><strong>${aliases}</strong><small>Ranking agrupa pelo identificador, não pelo nome.</small></div><div class="audititem card ok"><small>Empenho líquido</small><strong>${brl(net(e))}</strong><small>Empenhado + reforço − anulação.</small></div><div class="audititem card ok"><small>Receita líquida</small><strong>${brl(r.reduce((a,x)=>a+n(x.valor),0))}</strong><small>Inclui deduções negativas.</small></div></div><div class="note card" style="margin-top:10px">Auditoria é de consistência da base carregada. Não substitui auditoria contábil, jurídica ou de regularidade da contratação. Eventos contábeis são mantidos separadamente e não devem ser somados como se fossem gastos distintos.</div>`}
function render(){cards();$("#painel").hidden=tab!=="painel";$("#tableSec").hidden=!['despesas','receitas','fornecedores'].includes(tab);$("#auditSec").hidden=tab!=="auditoria";let count=0;if(tab==="painel")renderPanel();else if(tab==="auditoria")audit();else count=renderTable();$("#status").textContent=(count?count.toLocaleString("pt-BR")+" linhas exibidas • ":"")+"dados armazenados localmente neste aparelho • v0.3.1"}
async function importData(raw,mesNum){let a=typeof raw==="string"?JSON.parse(raw.replace(/^```(?:json)?\s*/,"").replace(/\s*```$/,"").trim()):raw;if(!Array.isArray(a)||!a.length)throw Error("JSON sem registros");let isD="evento" in a[0],ano=+$("#ano").value;if(isD){db.despesas=db.despesas.filter(x=>!(x.ano===ano&&x.mesNum===mesNum));db.despesas.push(...a.map(x=>({ano,mesNum,mes:x.mes||MONTHS[mesNum],orgao:x.orgao||"",evento:x.evento||"",empenho:x.nr_empenho||"",fornecedorId:x.id_fornecedor||"",fornecedor:x.nm_fornecedor||"",data:x.dt_emissao_despesa||"",valor:+String(x.vl_despesa||0).replace(/\./g,"").replace(",",".")})))}else{db.receitas=db.receitas.filter(x=>!(x.ano===ano&&x.mesNum===mesNum));db.receitas.push(...a.map(x=>({ano,mesNum,mes:x.mes||MONTHS[mesNum],orgao:x.orgao||"",fonte:x.ds_fonte_recurso||"",aplicacao:x.ds_cd_aplicacao_fixo||"",alinea:x.ds_alinea||"",subalinea:x.ds_subalinea||"",valor:+String(x.vl_arrecadacao||0).replace(/\./g,"").replace(",",".")})))}await save();render()}
function download(name,text,type="application/json"){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("#backupBtn").onclick=()=>download(`tcesp-mendonca-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(db));$("#restore").onchange=async e=>{let x=JSON.parse(await e.target.files[0].text());if(!x.despesas||!x.receitas)return alert("Backup inválido");db=x;await save();render();alert("Backup restaurado.")};$("#resetBtn").onclick=async()=>{if(confirm("Restaurar a base original Jan–Jul/2026 e apagar importações locais posteriores?")){db=structuredClone(window.SEED_DATA);await save();render()}};
$("#csvBtn").onclick=()=>{let table=$("#tableSec table");if(table.hidden||tab==="painel"||tab==="auditoria")return alert("Abra Despesas, Receitas ou Fornecedores.");let rows=[...table.querySelectorAll("tr")].map(tr=>[...tr.children].map(td=>'"'+td.innerText.replace(/"/g,'""')+'"').join(";"));download(`tcesp-${tab}.csv`,"\ufeff"+rows.join("\n"),"text/csv;charset=utf-8")};
for(let i=1;i<=12;i++)$("#mes").insertAdjacentHTML("beforeend",`<option value="${i}">${MONTHS[i]}</option>`);document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");tab=b.dataset.tab;render()});["mes","ano","orgao","q"].forEach(id=>$("#"+id).addEventListener(id==="q"?"input":"change",render));
$("#file").onchange=async e=>{let m=+$("#mes").value;if(!m)return alert("Selecione o mês que será substituído.");try{for(let f of e.target.files)await importData(await f.text(),m);alert("Importação concluída. O mês correspondente foi substituído, preservando duplicidades legítimas.")}catch(err){alert("Falha: "+err.message)}};
$("#apiBtn").onclick=async()=>{let m=+$("#mes").value;if(!m)return alert("Selecione um mês.");let base="https://transparencia.tce.sp.gov.br/api/json";try{let [d,r]=await Promise.all([fetch(`${base}/despesas/mendonca/${$("#ano").value}/${m}`).then(x=>x.json()),fetch(`${base}/receitas/mendonca/${$("#ano").value}/${m}`).then(x=>x.json())]);await importData(d,m);await importData(r,m);alert("Mês atualizado integralmente.")}catch(e){alert("A API não respondeu ou o navegador bloqueou a consulta. Use Importar JSON. Detalhe: "+e.message)}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");let deferred;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("#installBtn").hidden=false});$("#installBtn").onclick=async()=>{if(deferred){deferred.prompt();deferred=null}};
(async()=>{try{db=await idbGet();if(!db){let old=localStorage.getItem("tcesp-data");db=old?JSON.parse(old):structuredClone(window.SEED_DATA);await save();localStorage.removeItem("tcesp-data")}}catch(e){db=structuredClone(window.SEED_DATA);console.warn(e)}render();addEventListener("resize",()=>tab==="painel"&&renderPanel())})();
