const MONTHS=["","Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"],$=s=>document.querySelector(s);let tab="painel",db,compareReal=false,renderToken=0;
const DBN="tcesp-mendonca-v6",STORE="dados",KEY="base";
function idbOpen(){return new Promise((res,rej)=>{let r=indexedDB.open(DBN,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function idbGet(){let d=await idbOpen();return new Promise((res,rej)=>{let r=d.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function save(){let d=await idbOpen();return new Promise((res,rej)=>{let r=d.transaction(STORE,"readwrite").objectStore(STORE).put(db,KEY);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function brl(v){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0)} function n(v){return +v||0} function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function orgMatch(raw,filter){if(filter==="Todos")return true;let o=String(raw||"").toUpperCase();if(filter==="Prefeitura")return o.includes("PREFEITURA");if(filter==="Câmara")return o.includes("CÂMARA")||o.includes("CAMARA");return true}
function baseFilt(arr,withOrg=false){let m=+$("#mes").value,q=$("#q").value.toLowerCase(),o=$("#orgao").value;return arr.filter(x=>x.ano==+$("#ano").value&&(!m||x.mesNum==m)&&(!withOrg||orgMatch(x.orgao,o))&&(!q||JSON.stringify(x).toLowerCase().includes(q)))}
function evSums(d){let e={};d.forEach(x=>e[x.evento]=(e[x.evento]||0)+n(x.valor));return e} function net(e){return n(e.Empenhado)+n(e.Reforço)-n(e.Anulação)}
function supplierGroups(d){let g={};d.forEach(x=>{let id=x.fornecedorId||("NOME:"+(x.fornecedor||"(sem nome)")),k=id;g[k]??={id,nome:x.fornecedor||"(sem nome)",e:{}};if((x.fornecedor||"").length>g[k].nome.length)g[k].nome=x.fornecedor;g[k].e[x.evento]=(g[k].e[x.evento]||0)+n(x.valor)});return Object.values(g)}
function syncYears(){
  let years=[...new Set([...(db?.exercicios||[]),...(db?.despesas||[]).map(x=>+x.ano),...(db?.receitas||[]).map(x=>+x.ano)])].filter(Number.isFinite).sort((a,b)=>b-a);
  db.exercicios=years;
  let sel=$("#ano"),cur=+sel.value||years[0]||new Date().getFullYear();
  sel.innerHTML=years.map(y=>`<option value="${y}">${y}</option>`).join("");
  if(years.includes(cur))sel.value=String(cur); else if(years.length)sel.value=String(years[0]);
}
function cards(){let d=baseFilt(db.despesas,true),r=baseFilt(db.receitas,false),e=evSums(d),rec=r.reduce((a,x)=>a+n(x.valor),0),nl=net(e),saldo=rec-nl;$("#cards").innerHTML=[["Receita",rec],["Empenhado",e.Empenhado],["Reforço",e.Reforço],["Anulação",e.Anulação],["Empenho líquido",nl],["Liquidado",e["Valor Liquidado"]],["Pago",e["Valor Pago"]]].map((x,i)=>`<div class="metric card ${i===4?'emph':''}"><small>${x[0]}</small><strong>${brl(x[1])}</strong></div>`).join("")+`<div class="metric card emph"><small>Receita − empenho líquido</small><strong>${brl(saldo)}</strong></div>`}
function canvasSetup(c){let r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=r.height*dpr;let x=c.getContext("2d");x.scale(dpr,dpr);return {x,w:r.width,h:r.height}}
function pie(c,data){let {x,w,h}=canvasSetup(c),tot=data.reduce((a,b)=>a+b.v,0),cx=w*.38,cy=h*.48,R=Math.min(w,h)*.32,a=-Math.PI/2,colors=["#1565c0","#ef5350","#f9a825","#2e7d32","#7e57c2","#ef6c00","#00838f","#d81b60","#6d4c41","#546e7a","#43a047"];data.forEach((z,i)=>{let da=tot?z.v/tot*Math.PI*2:0;x.beginPath();x.moveTo(cx,cy);x.arc(cx,cy,R,a,a+da);x.closePath();x.fillStyle=colors[i%colors.length];x.fill();a+=da});x.font="11px Segoe UI";data.slice(0,11).forEach((z,i)=>{let yy=18+i*25,xx=w*.72;x.fillStyle=colors[i%colors.length];x.fillRect(xx,yy,10,10);x.fillStyle="#26333d";let nm=z.n.length>24?z.n.slice(0,23)+"…":z.n;x.fillText(nm,xx+15,yy+9);x.fillStyle="#66727e";x.fillText((tot?z.v/tot*100:0).toFixed(1).replace(".",",")+"%",xx+15,yy+21)})}
function lines(c,series){let {x,w,h}=canvasSetup(c),pad={l:55,r:15,t:18,b:35},vals=series.flatMap(s=>s.v),max=Math.max(...vals,1),min=Math.min(0,...vals),colors=["#17324d","#2f6fa5","#8b5e3c"];x.font="10px Segoe UI";x.strokeStyle="#dfe5e9";for(let i=0;i<=4;i++){let y=pad.t+(h-pad.t-pad.b)*i/4;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();let v=max-(max-min)*i/4;x.fillStyle="#66727e";x.fillText((v/1e6).toFixed(1)+" mi",3,y+3)}let months=Array.from({length:12},(_,i)=>i+1).filter(m=>!+$("#mes").value||m==+$("#mes").value);months.forEach((m,i)=>{let xx=pad.l+(w-pad.l-pad.r)*(months.length===1?.5:i/(months.length-1));x.fillStyle="#66727e";x.fillText(MONTHS[m].slice(0,3),xx-8,h-12)});series.forEach((s,si)=>{x.strokeStyle=colors[si];x.lineWidth=2;x.beginPath();s.v.forEach((v,i)=>{let xx=pad.l+(w-pad.l-pad.r)*(s.v.length===1?.5:i/(s.v.length-1)),yy=pad.t+(max-v)/(max-min||1)*(h-pad.t-pad.b);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke()})}
function bars(c,data){let {x,w,h}=canvasSetup(c),pad={l:160,r:15,t:10,b:15},max=Math.max(...data.map(z=>z.v),1),bh=(h-pad.t-pad.b)/data.length*.65,gap=(h-pad.t-pad.b)/data.length;x.font="10px Segoe UI";data.forEach((z,i)=>{let y=pad.t+i*gap;x.fillStyle="#2f6fa5";x.fillRect(pad.l,y,(w-pad.l-pad.r)*z.v/max,bh);x.fillStyle="#26333d";let nm=z.n.length>24?z.n.slice(0,23)+"…":z.n;x.fillText(nm,3,y+bh*.75);x.fillText((z.v/1e6).toFixed(2).replace(".",",")+" mi",pad.l+4,y+bh*.75)})}
function annualBars(c,rows){let {x,w,h}=canvasSetup(c),pad={l:54,r:12,t:24,b:42},vals=rows.flatMap(z=>[z.rec,z.net,z.paid]),max=Math.max(...vals,1),colors=["#17324d","#2f6fa5","#8b5e3c"],gw=(w-pad.l-pad.r)/Math.max(rows.length,1),bw=Math.max(5,Math.min(18,gw*.22));x.font="10px Segoe UI";x.strokeStyle="#dfe5e9";for(let i=0;i<=4;i++){let y=pad.t+(h-pad.t-pad.b)*i/4;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.fillStyle="#66727e";x.fillText(((max*(4-i)/4)/1e6).toFixed(0)+" mi",3,y+3)}rows.forEach((z,i)=>{let cx=pad.l+gw*(i+.5);[z.rec,z.net,z.paid].forEach((v,j)=>{let bh=(h-pad.t-pad.b)*v/max;x.fillStyle=colors[j];x.fillRect(cx+(j-1)*bw-bw*.45,h-pad.b-bh,bw*.9,bh)});x.fillStyle="#66727e";x.fillText(String(z.y),cx-12,h-17)});[["Receita",colors[0]],["Emp. líquido",colors[1]],["Pago",colors[2]]].forEach((z,i)=>{let xx=pad.l+i*105;x.fillStyle=z[1];x.fillRect(xx,5,10,10);x.fillStyle="#26333d";x.fillText(z[0],xx+14,14)})}
function growthLines(c,rows){let {x,w,h}=canvasSetup(c),pad={l:48,r:12,t:24,b:42},vals=rows.flatMap(z=>[z.recG,z.paidG]).filter(Number.isFinite);if(!vals.length)return;let max=Math.max(5,...vals),min=Math.min(-5,...vals),colors=["#17324d","#8b5e3c"],gw=(w-pad.l-pad.r)/Math.max(rows.length-1,1);x.font="10px Segoe UI";x.strokeStyle="#dfe5e9";for(let i=0;i<=4;i++){let y=pad.t+(h-pad.t-pad.b)*i/4,v=max-(max-min)*i/4;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.fillStyle="#66727e";x.fillText(v.toFixed(0)+"%",3,y+3)}rows.forEach((z,i)=>{let xx=pad.l+gw*i;x.fillStyle="#66727e";x.fillText(String(z.y),xx-12,h-17)});[["Receita",'recG'],["Pago",'paidG']].forEach((q,si)=>{x.strokeStyle=colors[si];x.lineWidth=2;x.beginPath();let started=false;rows.forEach((z,i)=>{let v=z[q[1]];if(!Number.isFinite(v))return;let xx=pad.l+gw*i,yy=pad.t+(max-v)/(max-min||1)*(h-pad.t-pad.b);started?x.lineTo(xx,yy):(x.moveTo(xx,yy),started=true)});x.stroke();x.fillStyle=colors[si];x.fillRect(pad.l+si*90,5,10,10);x.fillStyle="#26333d";x.fillText(q[0],pad.l+14+si*90,14)})}
function renderPanel(){const token=++renderToken,selectedYear=+$("#ano").value;let d=baseFilt(db.despesas,true),r=baseFilt(db.receitas,false),groups=supplierGroups(d),paid=groups.map(g=>({n:g.nome,v:n(g.e["Valor Pago"]),id:g.id})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v),top10=paid.slice(0,10),others=paid.slice(10).reduce((a,x)=>a+x.v,0);if(others>0)top10.push({n:"Demais credores",v:others});let months=Array.from({length:12},(_,i)=>i+1).filter(m=>!+$("#mes").value||m==+$("#mes").value),monthly=(kind)=>months.map(m=>{if(kind==="rec")return db.receitas.filter(x=>x.ano==+$("#ano").value&&x.mesNum==m).reduce((a,x)=>a+n(x.valor),0);let dd=db.despesas.filter(x=>x.ano==+$("#ano").value&&x.mesNum==m&&orgMatch(x.orgao,$("#orgao").value)),e=evSums(dd);return kind==="net"?net(e):n(e["Valor Pago"])});
$("#painel").innerHTML=`<section class="chartcard card"><h3>Despesa paga por credor — ${selectedYear}</h3><p>10 maiores credores + demais, conforme o filtro atual.</p><div class="chartbox"><canvas id="pie"></canvas></div></section><section class="chartcard card"><h3>Receita × empenho líquido × pago — ${selectedYear}</h3><p>Evolução mensal. Empenho líquido = empenhado + reforço − anulação.</p><div class="chartbox"><canvas id="line"></canvas></div><div class="barlegend">Receita • Empenho líquido • Pago</div></section><section class="chartcard card"><h3>40 maiores pagamentos — ${selectedYear}</h3><p>Ranking por credor, agrupado prioritariamente pelo identificador/CNPJ.</p><div class="chartbox" style="height:1040px"><canvas id="bars"></canvas></div></section><section class="rank card"><h3>Ranking — 40 maiores credores por valor pago — ${selectedYear}</h3><div class="rankgrid">${paid.slice(0,40).map((z,i)=>`<div class="rankrow"><span class="badge">${i+1}</span><span>${esc(z.n)}<small style="display:block;color:#77838d">${esc(z.id)}</small></span><b>${brl(z.v)}</b></div>`).join("")}</div></section>`;requestAnimationFrame(()=>{if(token!==renderToken||selectedYear!==+$("#ano").value)return;pie($("#pie"),top10);lines($("#line"),[{v:monthly("rec")},{v:monthly("net")},{v:monthly("paid")}]);bars($("#bars"),paid.slice(0,40))})}
function renderTable(){let d=baseFilt(db.despesas,true),r=baseFilt(db.receitas,false),rows=[],heads=[];if(tab==="despesas"){heads=["Valor","Mês","Evento","Empenho","Data","Órgão","Fornecedor","Identificação"];rows=d.sort((a,b)=>b.valor-a.valor).map(x=>[brl(x.valor),x.mes,x.evento,x.empenho,x.data,x.orgao,x.fornecedor,x.fornecedorId])}if(tab==="receitas"){heads=["Valor","Mês","Fonte","Aplicação","Natureza / alínea","Subalínea"];rows=r.sort((a,b)=>b.valor-a.valor).map(x=>[brl(x.valor),x.mes,x.fonte,x.aplicacao,x.alinea,x.subalinea])}if(tab==="fornecedores"){heads=["Fornecedor","Identificação","Empenhado","Reforço","Anulação","Empenho líquido","Liquidado","Pago"];rows=supplierGroups(d).map(g=>[g.nome,g.id,brl(g.e.Empenhado),brl(g.e.Reforço),brl(g.e.Anulação),brl(net(g.e)),brl(g.e["Valor Liquidado"]),brl(g.e["Valor Pago"])]).sort((a,b)=>money(b[7])-money(a[7]))}$("#thead").innerHTML="<tr>"+heads.map(h=>`<th>${h}</th>`).join("")+"</tr>";$("#tbody").innerHTML=rows.map(r=>"<tr>"+r.map(v=>`<td>${esc(v)}</td>`).join("")+"</tr>").join("");return rows.length}
function money(s){return +(s||"").replace(/[^\d,-]/g,"").replace(/\./g,"").replace(",",".")}
function audit(){let d=baseFilt(db.despesas,true),r=baseFilt(db.receitas,false),e=evSums(d),exactDup=a=>{let s=new Set(),c=0;a.forEach(x=>{let k=JSON.stringify(x);s.has(k)?c++:s.add(k)});return c},zero=d.filter(x=>n(x.valor)===0).length,negL=d.filter(x=>x.evento==="Valor Liquidado"&&x.valor<0).length,negP=d.filter(x=>x.evento==="Valor Pago"&&x.valor<0).length,negR=r.filter(x=>x.valor<0).length,ids={};d.forEach(x=>{if(x.fornecedorId)(ids[x.fornecedorId]??=new Set()).add(x.fornecedor)});let aliases=Object.values(ids).filter(s=>s.size>1).length;
$("#auditSec").innerHTML=`<div class="auditgrid"><div class="audititem card ok"><small>Registros de despesas</small><strong>${d.length.toLocaleString("pt-BR")}</strong><small>Filtro atual</small></div><div class="audititem card ${exactDup(d)?'warn':'ok'}"><small>Duplicatas exatas — despesas</small><strong>${exactDup(d)}</strong><small>Não são removidas automaticamente.</small></div><div class="audititem card ${exactDup(r)?'warn':'ok'}"><small>Duplicatas exatas — receitas</small><strong>${exactDup(r)}</strong><small>Preservadas: a API não fornece ID transacional.</small></div><div class="audititem card warn"><small>Eventos de valor zero</small><strong>${zero}</strong><small>Informativos/atípicos; preservados.</small></div><div class="audititem card warn"><small>Estornos de liquidação / pagamento</small><strong>${negL} / ${negP}</strong><small>Valores negativos preservados nos totais.</small></div><div class="audititem card warn"><small>Receitas negativas</small><strong>${negR}</strong><small>Deduções preservadas no total líquido.</small></div><div class="audititem card warn"><small>Identificadores com grafias distintas</small><strong>${aliases}</strong><small>Ranking agrupa pelo identificador, não pelo nome.</small></div><div class="audititem card ok"><small>Empenho líquido</small><strong>${brl(net(e))}</strong><small>Empenhado + reforço − anulação.</small></div><div class="audititem card ok"><small>Receita líquida</small><strong>${brl(r.reduce((a,x)=>a+n(x.valor),0))}</strong><small>Inclui deduções negativas.</small></div></div><div class="note card" style="margin-top:10px">Auditoria é de consistência da base carregada. Não substitui auditoria contábil, jurídica ou de regularidade da contratação. Eventos contábeis são mantidos separadamente e não devem ser somados como se fossem gastos distintos.</div>${renderOfficialAuditFindings()}`}
function renderOfficialAuditFindings(){let all=Array.isArray(window.TCESP_AUDIT_FINDINGS)?window.TCESP_AUDIT_FINDINGS:[],y=+$("#ano").value,items=all.filter(x=>+x.year===y);if(!items.length)return `<section class="officialaudit card"><h2>Contas anuais — fiscalização oficial do TCESP</h2><p class="muted">Não há parecer/acórdão cadastrado neste painel para o exercício ${y}. A ausência aqui não significa ausência de fiscalização ou de processo no TCESP.</p></section>`;return items.map(a=>`<section class="officialaudit card"><div class="audithead"><div><small>FISCALIZAÇÃO OFICIAL • TCESP</small><h2>Contas anuais — ${esc(a.year)}</h2><p>${esc(a.process||"")} • sessão ${esc(a.sessionDate||"")}</p></div><span class="decisiontag">${esc(a.decision||"")}</span></div><div class="officialmetrics">${(a.indicators||[]).map(i=>`<div><small>${esc(i.label)}</small><strong>${esc(i.value)}</strong><span>${esc(i.detail||"")}</span></div>`).join("")}</div><h3>Achados e observações do TCESP</h3><div class="findings">${(a.findings||[]).map(f=>`<article class="finding ${f.level==='positive'?'positive':'attention'}"><b>${esc(f.area)}</b><p>${esc(f.text)}</p></article>`).join("")}</div><div class="sourcebox"><b>Fonte:</b> ${esc(a.source||"TCESP")}<br><small>${esc(a.sourceNote||"")}</small></div><p class="methodnote">Esta seção reproduz, de forma resumida, informações do documento oficial cadastrado para o exercício. Ela é independente da auditoria automatizada de consistência da base acima e não transforma apontamentos do Tribunal em conclusões próprias do painel.</p></section>`).join("")}

function yearTotals(y){let d=db.despesas.filter(x=>x.ano==y&&orgMatch(x.orgao,$("#orgao").value)),r=db.receitas.filter(x=>x.ano==y),e=evSums(d);return {y,rec:r.reduce((a,x)=>a+n(x.valor),0),emp:n(e.Empenhado),net:net(e),liq:n(e["Valor Liquidado"]),paid:n(e["Valor Pago"]),dr:d.length,rr:r.length}}
const IPCA={2014:6.41,2015:10.67,2016:6.29,2017:2.95,2018:3.75,2019:4.31,2020:4.52,2021:10.06,2022:5.79,2023:4.62,2024:4.83,2025:4.26};
function ipcaFactorTo2025(y){if(y>=2025)return 1;let f=1;for(let a=y+1;a<=2025;a++)f*=1+(IPCA[a]||0)/100;return f}
function revenueCategory(r){let t=[r.fonte,r.aplicacao,r.alinea,r.subalinea].join(" ").toUpperCase();if(/FPM|FUNDO DE PARTICIPA.C..O DOS MUNIC.PIOS/.test(t))return "FPM";if(/ICMS/.test(t))return "ICMS";if(/FUNDEB/.test(t))return "Fundeb";if(/SUS|SA.DE/.test(t))return "SUS / Saúde";if(/ISSQN|ISS\b|SERVI.OS DE QUALQUER NATUREZA/.test(t))return "ISS";if(/IPTU|PROPRIEDADE PREDIAL|PROPRIEDADE TERRITORIAL URBANA/.test(t))return "IPTU";if(/ITBI|TRANSMISS.O.*BENS IM.VEIS/.test(t))return "ITBI";if(/IPVA/.test(t))return "IPVA";if(/ITR|PROPRIEDADE TERRITORIAL RURAL/.test(t))return "ITR";if(/CONV.NIO|CONVENIO|TRANSFER.NCIA/.test(t))return "Outras transferências";return "Demais receitas"}
function revenueComposition(y){let g={};db.receitas.filter(r=>r.ano==y).forEach(r=>{let k=revenueCategory(r);g[k]=(g[k]||0)+n(r.valor)});return Object.entries(g).map(([n,v])=>({n,v})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v)}
function paidComposition(y){let d=db.despesas.filter(x=>x.ano==y),g=supplierGroups(d).map(x=>({n:x.nome,v:n(x.e["Valor Pago"])})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v),top=g.slice(0,8),other=g.slice(8).reduce((a,x)=>a+x.v,0);if(other)top.push({n:"Demais credores",v:other});return top}
function compareYears(){let ys=[...new Set([...(db.exercicios||[]),...db.despesas.map(x=>+x.ano),...db.receitas.map(x=>+x.ano)])].filter(Boolean).sort((a,b)=>a-b),want=[...new Set([2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,...ys])].sort((a,b)=>a-b),raw=want.map(yearTotals),readyRaw=raw.filter(x=>x.dr||x.rr),ready=readyRaw.map(x=>{let f=compareReal&&x.y<=2025?ipcaFactorTo2025(x.y):1;return {...x,rec:x.rec*f,net:x.net*f,liq:x.liq*f,paid:x.paid*f}}),full=ready.filter(x=>{let ms=new Set(db.receitas.filter(r=>r.ano==x.y).map(r=>r.mesNum));return ms.size===12}),growth=full.map((x,i)=>({y:x.y,recG:i?((x.rec/full[i-1].rec)-1)*100:NaN,paidG:i?((x.paid/full[i-1].paid)-1)*100:NaN})),latestFull=[...full].reverse().find(x=>x.y<=2025),selectedY=+$("#ano").value,selectedReady=readyRaw.some(x=>x.y===selectedY&&(x.dr||x.rr)),compY=selectedReady?selectedY:(latestFull?.y||2025),revComp=revenueComposition(compY),paidComp=paidComposition(compY),mode=compareReal?"valores reais, corrigidos pelo IPCA para reais de dez/2025":"valores nominais";
$("#compareSec").innerHTML=`<div class="explain-hero card"><h2>Comparar exercícios</h2><p>Comparação gráfica e numérica dos exercícios armazenados neste aparelho. Exercícios parciais aparecem no gráfico de valores, mas não entram no cálculo de crescimento anual.</p><div class="modeSwitch"><button id="nominalBtn" class="${compareReal?'':'active'}">Valores nominais</button><button id="realBtn" class="${compareReal?'active':''}">Corrigidos pelo IPCA</button></div><small class="ipcanote">Modo atual: ${mode}. IPCA anual oficial do IBGE; 2026 permanece nominal por ser exercício em curso.</small></div>${ready.length?`<div class="comparecharts"><section class="chartcard card"><h3>Receita × empenho líquido × pago</h3><p>Totais dos meses disponíveis em cada exercício — ${mode}.</p><div class="chartbox"><canvas id="annualBars"></canvas></div></section><section class="chartcard card"><h3>Crescimento ${compareReal?'real':'nominal'} anual</h3><p>Variação de receita e pagamentos entre exercícios completos consecutivos.</p><div class="chartbox"><canvas id="growthLines"></canvas></div></section></div><div class="comparecharts"><section class="chartcard card"><h3>Composição da receita — ${compY}</h3><p>Classificação analítica pelas descrições de fonte, alínea e subalínea da API do TCESP.</p><div class="chartbox"><canvas id="revPie"></canvas></div></section><section class="chartcard card"><h3>Composição da despesa paga — ${compY}</h3><p>8 maiores credores + demais. A API usada pelo painel não traz função orçamentária da despesa.</p><div class="chartbox"><canvas id="paidPie"></canvas></div></section></div>`:""}<div class="comparegrid">${ready.slice().reverse().map(x=>`<div class="card compareyear"><h3>${x.y}${x.y===2026?' <small>(parcial)</small>':''}</h3>${x.dr||x.rr?`<small>${x.dr.toLocaleString("pt-BR")} despesas • ${x.rr.toLocaleString("pt-BR")} receitas</small><p><b>Receita</b><span>${brl(x.rec)}</span></p><p><b>Empenho líquido</b><span>${brl(x.net)}</span></p><p><b>Liquidado</b><span>${brl(x.liq)}</span></p><p><b>Pago</b><span>${brl(x.paid)}</span></p>`:`<small>Dados ainda não carregados.</small>`}</div>`).join("")}</div>${ready.length>1?`<div class="note card">Os totais abrangem os meses existentes em cada exercício. Um exercício parcial não deve ser comparado diretamente com 12 meses de um exercício encerrado. A correção pelo IPCA usa as taxas anuais do IBGE e expressa os exercícios encerrados em poder de compra de dezembro de 2025.</div>`:""}`;
$("#nominalBtn")?.addEventListener("click",()=>{compareReal=false;compareYears()});$("#realBtn")?.addEventListener("click",()=>{compareReal=true;compareYears()});if(ready.length)requestAnimationFrame(()=>{annualBars($("#annualBars"),ready);if(growth.length>1)growthLines($("#growthLines"),growth);if(revComp.length)pie($("#revPie"),revComp);if(paidComp.length)pie($("#paidPie"),paidComp)})}
function render(){syncYears();cards();renderFreshness();$("#painel").hidden=tab!=="painel";$("#tableSec").hidden=!["despesas","receitas","fornecedores"].includes(tab);$("#auditSec").hidden=tab!=="auditoria";$("#compareSec").hidden=tab!=="comparar";$("#entendaSec").hidden=tab!=="entenda";let count=0;if(tab==="painel")renderPanel();else if(tab==="auditoria")audit();else if(tab==="comparar")compareYears();else if(tab==="entenda"){}else count=renderTable();$("#status").textContent=(count?count.toLocaleString("pt-BR")+" linhas exibidas • ":"")+"base histórica incorporada ao site + atualizações locais • v0.8.6"}
async function importData(raw,mesNum,anoOverride){let a=typeof raw==="string"?JSON.parse(raw.replace(/^```(?:json)?\s*/,"").replace(/\s*```$/,"").trim()):raw;if(!Array.isArray(a)||!a.length)throw Error("JSON sem registros");let isD="evento" in a[0],ano=anoOverride??+$("#ano").value;if(isD){db.despesas=db.despesas.filter(x=>!(x.ano===ano&&x.mesNum===mesNum));db.despesas.push(...a.map(x=>({ano,mesNum,mes:x.mes||MONTHS[mesNum],orgao:x.orgao||"",evento:x.evento||"",empenho:x.nr_empenho||"",fornecedorId:x.id_fornecedor||"",fornecedor:x.nm_fornecedor||"",data:x.dt_emissao_despesa||"",valor:+String(x.vl_despesa||0).replace(/\./g,"").replace(",",".")})))}else{db.receitas=db.receitas.filter(x=>!(x.ano===ano&&x.mesNum===mesNum));db.receitas.push(...a.map(x=>({ano,mesNum,mes:x.mes||MONTHS[mesNum],orgao:x.orgao||"",fonte:x.ds_fonte_recurso||"",aplicacao:x.ds_cd_aplicacao_fixo||"",alinea:x.ds_alinea||"",subalinea:x.ds_subalinea||"",valor:+String(x.vl_arrecadacao||0).replace(/\./g,"").replace(",",".")})))}await save();render()}
function download(name,text,type="application/json"){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("#backupBtn").onclick=()=>download(`tcesp-mendonca-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(db));$("#restore").onchange=async e=>{let x=JSON.parse(await e.target.files[0].text());if(!x.despesas||!x.receitas)return alert("Backup inválido");db=x;await save();render();alert("Backup restaurado.")};$("#resetBtn").onclick=async()=>{if(confirm("Restaurar a base histórica incorporada ao site e apagar apenas as atualizações locais posteriores?")){db=structuredClone(window.SEED_DATA);await save();render()}};
$("#csvBtn").onclick=()=>{let table=$("#tableSec table");if(table.hidden||tab==="painel"||tab==="auditoria"||tab==="entenda")return alert("Abra Despesas, Receitas ou Fornecedores.");let rows=[...table.querySelectorAll("tr")].map(tr=>[...tr.children].map(td=>'"'+td.innerText.replace(/"/g,'""')+'"').join(";"));download(`tcesp-${tab}.csv`,"\ufeff"+rows.join("\n"),"text/csv;charset=utf-8")};
for(let i=1;i<=12;i++)$("#mes").insertAdjacentHTML("beforeend",`<option value="${i}">${MONTHS[i]}</option>`);function selectTab(t){let b=document.querySelector(`nav button[data-tab="${t}"]`);if(!b)return;document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");tab=t;if(location.hash!=="#"+t)history.replaceState(null,"","#"+t);render()} document.querySelectorAll("nav button").forEach(b=>b.addEventListener("click",()=>selectTab(b.dataset.tab)));["mes","ano","orgao","q"].forEach(id=>$("#"+id).addEventListener(id==="q"?"input":"change",render));
$("#file").onchange=async e=>{let m=+$("#mes").value;if(!m)return alert("Selecione o mês que será substituído.");try{for(let f of e.target.files)await importData(await f.text(),m);alert("Importação concluída. O mês correspondente foi substituído, preservando duplicidades legítimas.")}catch(err){alert("Falha: "+err.message)}};
const MUNICIPIO_API="mendonca";
const AUDESP_2026={7:"2026-08-20",8:"2026-09-21",9:"2026-10-20",10:"2026-11-23"};
function fmtDT(v){if(!v)return "—";try{return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v))}catch{return v}}
function monthCoverage(y){let ms=[...new Set([...db.despesas.filter(x=>x.ano==y).map(x=>x.mesNum),...db.receitas.filter(x=>x.ano==y).map(x=>x.mesNum)])].filter(Boolean).sort((a,b)=>a-b);return ms}
function renderFreshness(){let el=$("#apiFreshness");if(!el)return;let y=+$("#ano").value,ms=monthCoverage(y),last=ms.length?Math.max(...ms):0,u=db.apiUpdates||{},k=last?`${y}-${String(last).padStart(2,"0")}`:"",info=k?u[k]:null,next=last<12?last+1:null,deadline=(y===2026&&next)?AUDESP_2026[next]:null;el.innerHTML=`<div><small>Último mês disponível no painel</small><strong>${last?MONTHS[last]+"/"+y:"Nenhum mês carregado"}</strong></div><div><small>Última atualização pela API</small><strong>${info?.loadedAt?fmtDT(info.loadedAt):"Ainda não registrada"}</strong></div><div><small>Última verificação automática</small><strong>${db.lastApiCheck?fmtDT(db.lastApiCheck):"Ainda não realizada"}</strong></div><div><small>${deadline?"Prazo AUDESP do próximo mês":"Próxima atualização"}</small><strong>${deadline?new Date(deadline+"T12:00:00").toLocaleDateString("pt-BR"):"Consultar TCESP"}</strong></div>`}
function markApiUpdate(y,m,d,r){db.apiUpdates??={};db.apiUpdates[`${y}-${String(m).padStart(2,"0")}`]={loadedAt:new Date().toISOString(),despesas:Array.isArray(d)?d.length:0,receitas:Array.isArray(r)?r.length:0}}
async function updateMonthFromApi(y,m,silent=false){let base="https://transparencia.tce.sp.gov.br/api/json",[d,r]=await Promise.all([fetchJson(`${base}/despesas/${MUNICIPIO_API}/${y}/${m}`),fetchJson(`${base}/receitas/${MUNICIPIO_API}/${y}/${m}`)]);if(!Array.isArray(d)||!d.length||!Array.isArray(r)||!r.length)throw Error("mês ainda sem dados completos na API");await importData(d,m,y);await importData(r,m,y);markApiUpdate(y,m,d,r);db.lastApiCheck=new Date().toISOString();await save();renderFreshness();if(!silent)alert("Mês atualizado integralmente.");return true}
async function autoCheckCurrentYear(){let y=new Date().getFullYear();if(y!==2026)return;let ms=monthCoverage(y),last=ms.length?Math.max(...ms):0,next=last+1,deadline=AUDESP_2026[next];if(!deadline)return;let today=new Date(),due=new Date(deadline+"T23:59:59");if(today<=due)return;let lastTry=db.autoCheck?.[`${y}-${next}`];if(lastTry&&Date.now()-new Date(lastTry).getTime()<20*60*60*1000)return;db.autoCheck??={};db.autoCheck[`${y}-${next}`]=new Date().toISOString();db.lastApiCheck=new Date().toISOString();await save();try{await updateMonthFromApi(y,next,true)}catch(e){console.info("TCESP: próximo mês ainda indisponível",e.message);renderFreshness()}}
async function fetchJson(url){let r=await fetch(url,{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);return r.json()}
async function loadYear(y){let base="https://transparencia.tce.sp.gov.br/api/json",ok=0,fail=[];$("#status").textContent=`Carregando ${y}: iniciando…`;for(let m=1;m<=12;m++){try{$("#status").textContent=`Carregando ${y}: mês ${m}/12 — despesas…`;let d=await fetchJson(`${base}/despesas/${MUNICIPIO_API}/${y}/${m}`);$("#ano").value=String(y);await importData(d,m,y);$("#status").textContent=`Carregando ${y}: mês ${m}/12 — receitas…`;let r=await fetchJson(`${base}/receitas/${MUNICIPIO_API}/${y}/${m}`);await importData(r,m,y);markApiUpdate(y,m,d,r);ok++}catch(e){fail.push(`${m}: ${e.message}`)}}await save();syncYears();render();if(fail.length)throw Error(`${ok}/12 meses concluídos. Falhas: ${fail.join("; ")}`);return ok}
$("#yearBtn").onclick=async()=>{let y=+$("#ano").value;if(!confirm(`Carregar os 12 meses de ${y} pelo TCESP? Os meses existentes desse exercício serão substituídos pelos dados retornados pela API.`))return;try{await loadYear(y);alert(`Exercício ${y} carregado com 12 meses.`)}catch(e){alert("Carga do exercício incompleta. Os meses concluídos foram preservados. "+e.message)}};
$("#addYearBtn").onclick=async()=>{let raw=prompt("Qual exercício deseja adicionar? Ex.: 2024"),y=+raw,now=new Date().getFullYear();if(!raw)return;if(!Number.isInteger(y)||y<2008||y>now)return alert(`Informe um ano entre 2008 e ${now}.`);db.exercicios=[...new Set([...(db.exercicios||[]),y])];await save();syncYears();$("#ano").value=String(y);render();if(confirm(`Exercício ${y} adicionado ao seletor. Deseja carregar agora os 12 meses pelo TCESP?`)){try{await loadYear(y);alert(`Exercício ${y} carregado.`)}catch(e){alert("Carga incompleta. "+e.message)}}};
$("#apiBtn").onclick=async()=>{let m=+$("#mes").value;if(!m)return alert("Selecione um mês.");let y=+$("#ano").value;try{await updateMonthFromApi(y,m,false)}catch(e){db.lastApiCheck=new Date().toISOString();await save();renderFreshness();alert("A API não respondeu, o mês ainda não está disponível ou o navegador bloqueou a consulta. Detalhe: "+e.message)}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");let deferred;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("#installBtn").hidden=false});$("#installBtn").onclick=async()=>{if(deferred){deferred.prompt();deferred=null}};

// v0.8.3 — consolida os arquivos históricos 2014–2019 no seed permanente.
// Os arquivos 2020–2026 já alimentam SEED_DATA diretamente.
if(window.TCESP_ANNUAL_DATA){
  for(const y of Object.keys(window.TCESP_ANNUAL_DATA)){
    const pack=window.TCESP_ANNUAL_DATA[y]||{};
    if(Array.isArray(pack.despesas)) window.SEED_DATA.despesas.push(...pack.despesas);
    if(Array.isArray(pack.receitas)) window.SEED_DATA.receitas.push(...pack.receitas);
  }
}
window.SEED_DATA.exercicios=[...new Set([
  ...(window.SEED_DATA.exercicios||[]),
  ...window.SEED_DATA.despesas.map(x=>+x.ano),
  ...window.SEED_DATA.receitas.map(x=>+x.ano)
])].filter(Boolean).sort((a,b)=>a-b);

(async()=>{try{
  db=await idbGet();
  if(!db){let old=localStorage.getItem("tcesp-data");db=old?JSON.parse(old):structuredClone(window.SEED_DATA);}
  // v0.8.3: instala uma única vez a base histórica incorporada (2014–2026).
  // Depois disso, novas versões preservam as atualizações locais/API.
  if(db?._bundleVersion!==window.SEED_DATA._bundleVersion){db=structuredClone(window.SEED_DATA);}
  // Autorrecuperação da migração v0.3: se a base local perdeu as despesas Jan–Jul/2026,
  // restaura somente as despesas do seed oficial, preservando receitas/importações locais.
  let validDesp=Array.isArray(db.despesas)&&db.despesas.some(x=>x&&x.ano==2026&&x.evento&&x.orgao);
  if(!validDesp){db.despesas=structuredClone(window.SEED_DATA.despesas);}
  if(!Array.isArray(db.receitas)||!db.receitas.length){db.receitas=structuredClone(window.SEED_DATA.receitas);}
  if(!Array.isArray(db.exercicios))db.exercicios=[];if(!db.apiUpdates)db.apiUpdates={};if(!db.autoCheck)db.autoCheck={};
  await save();localStorage.removeItem("tcesp-data");
}catch(e){db=structuredClone(window.SEED_DATA);console.warn(e)}
let ht=location.hash.slice(1);if(["painel","despesas","receitas","fornecedores","auditoria","comparar","entenda"].includes(ht)){tab=ht;document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));} render();setTimeout(()=>autoCheckCurrentYear(),1200);addEventListener("resize",()=>tab==="painel"&&renderPanel())})();
